// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdMqpK1GaMTL5TkT7uoElRDkLBOp-pRxc',
    appId: '1:572473803778:web:07fe5c0055bd7d4b9c131b',
    messagingSenderId: '572473803778',
    projectId: 'shop-x-df9ec',
    authDomain: 'shop-x-df9ec.firebaseapp.com',
    storageBucket: 'shop-x-df9ec.firebasestorage.app',
    measurementId: 'G-6KTDECVK7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqFlmUxvaJd3hZms6dhC9jwDQskepTSnM',
    appId: '1:572473803778:android:e969bfc66900bb589c131b',
    messagingSenderId: '572473803778',
    projectId: 'shop-x-df9ec',
    storageBucket: 'shop-x-df9ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfOQ6NXMk9J5DpxWzxCfL6ZaqqqQv4ZGs',
    appId: '1:572473803778:ios:c15b1a5993efe1a49c131b',
    messagingSenderId: '572473803778',
    projectId: 'shop-x-df9ec',
    storageBucket: 'shop-x-df9ec.firebasestorage.app',
    iosClientId: '572473803778-qdmbr2ti2ht42ppirnuifbt1saki0230.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfOQ6NXMk9J5DpxWzxCfL6ZaqqqQv4ZGs',
    appId: '1:572473803778:ios:c15b1a5993efe1a49c131b',
    messagingSenderId: '572473803778',
    projectId: 'shop-x-df9ec',
    storageBucket: 'shop-x-df9ec.firebasestorage.app',
    iosClientId: '572473803778-qdmbr2ti2ht42ppirnuifbt1saki0230.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdMqpK1GaMTL5TkT7uoElRDkLBOp-pRxc',
    appId: '1:572473803778:web:3a9572bf2e6508409c131b',
    messagingSenderId: '572473803778',
    projectId: 'shop-x-df9ec',
    authDomain: 'shop-x-df9ec.firebaseapp.com',
    storageBucket: 'shop-x-df9ec.firebasestorage.app',
    measurementId: 'G-MDBH15R7S3',
  );
}
